// AUTO-GENERATED by scripts/generate-entity-keys.cjs — do not hand-edit.
// Source of truth: the frozen MVP v1.0 taxonomy (Handbook Ch 08, Ch 25-A).
// Regenerate with: node scripts/generate-entity-keys.cjs

export const MEMORY_DOMAINS = ['ai', 'education', 'employment', 'event', 'finance', 'goal', 'health', 'identity', 'location', 'preference', 'project', 'relationship', 'skill', 'task', 'technology'] as const;
export type MemoryDomain = typeof MEMORY_DOMAINS[number];

export const ENTITY_KEYS = [
  'identity.name',
  'identity.nickname',
  'identity.language',
  'identity.timezone',
  'identity.birth_date',
  'identity.cultural_background',
  'location.country',
  'location.city',
  'location.region',
  'location.residence',
  'location.previous',
  'employment.organization',
  'employment.role',
  'employment.industry',
  'employment.status',
  'employment.work_style',
  'employment.experience',
  'education.institution',
  'education.field',
  'education.degree',
  'education.level',
  'education.status',
  'skill.technical',
  'skill.language',
  'skill.professional',
  'skill.learning',
  'project.name',
  'project.type',
  'project.status',
  'project.goal',
  'project.technology',
  'goal.personal',
  'goal.career',
  'goal.education',
  'goal.financial',
  'goal.health',
  'goal.timeline',
  'preference.general',
  'preference.communication_style',
  'preference.technology',
  'preference.food',
  'preference.entertainment',
  'preference.learning_style',
  'ai.response_style',
  'ai.workflow_preference',
  'ai.model_preference',
  'relationship.person',
  'relationship.role',
  'relationship.organization',
  'task.current',
  'task.deadline',
  'task.status',
  'event.personal',
  'event.professional',
  'event.deadline',
  'technology.device',
  'technology.software',
  'technology.account',
  'finance.goal',
  'health.preference',
] as const;

/**
 * Union of all 60 frozen entity keys (Handbook Ch 08). Enforced at the
 * database layer by a foreign key to entity_key_registry — this type is a
 * compile-time mirror for catching typos before a request ever reaches the
 * DB, not a replacement for the runtime FK constraint.
 */
export type EntityKey = typeof ENTITY_KEYS[number];

export const ENTITY_KEYS_BY_DOMAIN: Record<MemoryDomain, EntityKey[]> = {
  ai: ['ai.response_style', 'ai.workflow_preference', 'ai.model_preference'],
  education: ['education.institution', 'education.field', 'education.degree', 'education.level', 'education.status'],
  employment: ['employment.organization', 'employment.role', 'employment.industry', 'employment.status', 'employment.work_style', 'employment.experience'],
  event: ['event.personal', 'event.professional', 'event.deadline'],
  finance: ['finance.goal'],
  goal: ['goal.personal', 'goal.career', 'goal.education', 'goal.financial', 'goal.health', 'goal.timeline'],
  health: ['health.preference'],
  identity: ['identity.name', 'identity.nickname', 'identity.language', 'identity.timezone', 'identity.birth_date', 'identity.cultural_background'],
  location: ['location.country', 'location.city', 'location.region', 'location.residence', 'location.previous'],
  preference: ['preference.general', 'preference.communication_style', 'preference.technology', 'preference.food', 'preference.entertainment', 'preference.learning_style'],
  project: ['project.name', 'project.type', 'project.status', 'project.goal', 'project.technology'],
  relationship: ['relationship.person', 'relationship.role', 'relationship.organization'],
  skill: ['skill.technical', 'skill.language', 'skill.professional', 'skill.learning'],
  task: ['task.current', 'task.deadline', 'task.status'],
  technology: ['technology.device', 'technology.software', 'technology.account'],
};
